import { Channel } from './types';

export const mockChannels: Channel[] = [
  // TV KANALLARI (ULUSAL VE HABER)
  {
    id: 'tv-trt1',
    name: 'TRT 1',
    type: 'tv',
    url: 'https://tv-trt1.medya.trt.com.tr/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/TRT_1_logo_%282021-%29.svg/512px-TRT_1_logo_%282021-%29.svg.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-atv',
    name: 'ATV',
    type: 'tv',
    url: 'https://rnttwmjcin.turknet.ercdn.net/lcpmvefbyo/atv/atv_1080p.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Atv_logo.svg/512px-Atv_logo.svg.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-kanald',
    name: 'Kanal D',
    type: 'tv',
    url: 'https://demiroren.daioncdn.net/kanald/kanald.m3u8?app=kanald_web&ce=3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Kanal_D_logo.svg/512px-Kanal_D_logo.svg.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-showtv',
    name: 'Show TV',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/showtvnp/playlist.m3u8',
    logo: 'https://i.imgur.com/1l7SCCu.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-startv',
    name: 'Star TV',
    type: 'tv',
    url: 'https://dogus.daioncdn.net/startv/startv_720p.m3u8?app=a20ac41e-bdc3-4aa1-934d-26b484480ac9&ce=3&sid=8l4w3lst4co5',
    logo: 'https://i.imgur.com/9O3DHRB.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-tv8',
    name: 'TV8',
    type: 'tv',
    url: 'https://tv8.daioncdn.net/tv8/tv8.m3u8?app=7ddc255a-ef47-4e81-ab14-c0e5f2949788&ce=3',
    logo: 'https://upload.wikimedia.org/wikipedia/tr/thumb/6/68/Tv8_Yeni_Logo.png/512px-Tv8_Yeni_Logo.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-kanal7',
    name: 'Kanal 7',
    type: 'tv',
    url: 'https://kanal7-live.daioncdn.net/kanal7/kanal7.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Kanal_7_logo.svg/512px-Kanal_7_logo.svg.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-teve2',
    name: 'Teve2',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/teve2np/playlist.m3u8',
    logo: 'https://i.imgur.com/rsoSLih.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-beyaztv',
    name: 'Beyaz TV',
    type: 'tv',
    url: 'https://beyaztv-live.daioncdn.net/beyaztv/beyaztv.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Beyaz_TV_logo.svg/512px-Beyaz_TV_logo.svg.png',
    category: 'Ulusal',
  },
  {
    id: 'tv-trthaber',
    name: 'TRT Haber',
    type: 'tv',
    url: 'https://tv-trthaber.medya.trt.com.tr/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/TRT_Haber_Eyl%C3%BCl_2020_Logo.svg/512px-TRT_Haber_Eyl%C3%BCl_2020_Logo.svg.png',
    category: 'Haber',
  },
  {
    id: 'tv-ahaber',
    name: 'A Haber',
    type: 'tv',
    url: 'https://rnttwmjcin.turknet.ercdn.net/lcpmvefbyo/ahaber/ahaber.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/A_Haber_logo.svg/512px-A_Haber_logo.svg.png',
    category: 'Haber',
  },
  {
    id: 'tv-haberturk',
    name: 'Habertürk',
    type: 'tv',
    url: 'https://tv.ensonhaber.com/haberturk/haberturk.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Habert%C3%BCrk_TV_logo.svg/512px-Habert%C3%BCrk_TV_logo.svg.png',
    category: 'Haber',
  },
  {
    id: 'tv-ntv',
    name: 'NTV',
    type: 'tv',
    url: 'https://dogus.daioncdn.net/ntv/ntv.m3u8?app=ntv_web',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ntv_logo.svg/512px-Ntv_logo.svg.png',
    category: 'Haber',
  },
  {
    id: 'tv-halktv',
    name: 'Halk TV',
    type: 'tv',
    url: 'https://halktv-live.daioncdn.net/halktv/halktv.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Halk_TV_logo.svg/512px-Halk_TV_logo.svg.png',
    category: 'Haber',
  },
  {
    id: 'tv-tv100',
    name: 'TV100',
    type: 'tv',
    url: 'https://tv.ensonhaber.com/tv100/tv100.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/tr/thumb/0/0f/TV100_logo.png/512px-TV100_logo.png',
    category: 'Haber',
  },
  {
    id: 'tv-tele1',
    name: 'Tele1',
    type: 'tv',
    url: 'https://tele1-live.ercdn.net/tele1/tele1.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/tr/4/43/Tele1_logosu.png',
    category: 'Haber',
  },
  {
    id: 'tv-tgrthaber',
    name: 'TGRT Haber',
    type: 'tv',
    url: 'https://tgrthaber-live.daioncdn.net/tgrthaber/tgrthaber.m3u8',
    logo: 'https://i.imgur.com/PrxwKDw.png',
    category: 'Haber',
  },
  {
    id: 'tv-ulketv',
    name: 'Ülke TV',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/ulketvnp/playlist.m3u8',
    logo: 'https://i.imgur.com/wdWR7Qk.png',
    category: 'Haber',
  },
  {
    id: 'tv-bloomberght',
    name: 'Bloomberg HT',
    type: 'tv',
    url: 'https://tv.ensonhaber.com/bloomberght/bloomberght.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bloomberg_HT_logo.svg/512px-Bloomberg_HT_logo.svg.png',
    category: 'Ekonomi',
  },
  {
    id: 'tv-apara',
    name: 'A Para',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/apanp/playlist.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/A_Para_logo.svg/512px-A_Para_logo.svg.png',
    category: 'Ekonomi',
  },
  {
    id: 'tv-trtspor',
    name: 'TRT Spor',
    type: 'tv',
    url: 'https://tv-trtspor1.medya.trt.com.tr/master.m3u8',
    logo: 'https://i.imgur.com/6tv0zxh.png',
    category: 'Spor',
  },
  {
    id: 'tv-aspor',
    name: 'A Spor',
    type: 'tv',
    url: 'https://rnttwmjcin.turknet.ercdn.net/lcpmvefbyo/aspor/aspor.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/A_Spor_logo.svg/512px-A_Spor_logo.svg.png',
    category: 'Spor',
  },
  {
    id: 'tv-trtbelgesel',
    name: 'TRT Belgesel',
    type: 'tv',
    url: 'https://tv-trtbelgesel.medya.trt.com.tr/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/TRT_Belgesel_logo_%282019-%29.svg/512px-TRT_Belgesel_logo_%282019-%29.svg.png',
    category: 'Belgesel',
  },
  {
    id: 'tv-trt2',
    name: 'TRT 2',
    type: 'tv',
    url: 'https://tv-trt2.medya.trt.com.tr/master.m3u8',
    logo: 'https://i.imgur.com/iOCQdyD.png',
    category: 'Kültür Sanat',
  },
  {
    id: 'tv-trtcocuk',
    name: 'TRT Çocuk',
    type: 'tv',
    url: 'https://tv-trtcocuk.medya.trt.com.tr/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/TRT_%C3%87ocuk_logo_%282021%29.svg/512px-TRT_%C3%87ocuk_logo_%282021%29.svg.png',
    category: 'Çocuk',
  },
  {
    id: 'tv-minikacocuk',
    name: 'Minika Çocuk',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/minikacocuknp/playlist.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Minika_%C3%87ocuk_logo.svg/512px-Minika_%C3%87ocuk_logo.svg.png',
    category: 'Çocuk',
  },
  {
    id: 'tv-minikago',
    name: 'Minika GO',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/minikagonp/playlist.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Minika_GO_logo.svg/512px-Minika_GO_logo.svg.png',
    category: 'Çocuk',
  },
  {
    id: 'tv-kralpoptv',
    name: 'Kral Pop TV',
    type: 'tv',
    url: 'https://dogus.daioncdn.net/kralpoptv/kralpoptv.m3u8?app=kralpoptv_web',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Kral_Pop_TV_logo.svg/512px-Kral_Pop_TV_logo.svg.png',
    category: 'Müzik',
  },
  {
    id: 'tv-dreamturk',
    name: 'Dream Türk',
    type: 'tv',
    url: 'https://live.duhnet.tv/S2/HLS_LIVE/dreamturknp/playlist.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dream_T%C3%BCrk_logo.svg/512px-Dream_T%C3%BCrk_logo.svg.png',
    category: 'Müzik',
  },
  {
    id: 'tv-trtmuzik',
    name: 'TRT Müzik',
    type: 'tv',
    url: 'https://tv-trtmuzik.medya.trt.com.tr/master.m3u8',
    logo: 'https://i.imgur.com/JgUzRH8.png',
    category: 'Müzik',
  },
  {
    id: 'tv-redbull',
    name: 'Red Bull TV',
    type: 'tv',
    url: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    logo: 'https://jiotvimages.cdn.jio.com/dare_images/images/Red_Bull_TV.png',
    category: 'Yabancı Spor',
    country: 'us',
  },
  {
    id: 'tv-aljazeera',
    name: 'Al Jazeera',
    type: 'tv',
    url: 'https://live-hls-web-aje-fa.thehlive.com/AJE/index.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Aljazeera_eng.svg/512px-Aljazeera_eng.svg.png',
    category: 'Dünya / Haber',
    country: 'qa',
  },
  {
    id: 'tv-france24',
    name: 'France 24',
    type: 'tv',
    url: 'https://live.france24.com/hls/live/2037218-b/F24_EN_HI_HLS/master_2300.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/France_24_logo.svg/512px-France_24_logo.svg.png',
    category: 'Dünya / Haber',
    country: 'fr',
  },
  {
    id: 'tv-dw-eng',
    name: 'DW English',
    type: 'tv',
    url: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_logo.svg/512px-Deutsche_Welle_logo.svg.png',
    category: 'Dünya / Haber',
    country: 'de',
  },
  {
    id: 'tv-skynews-uk',
    name: 'Sky News',
    type: 'tv',
    url: 'https://skynewsau-live.akamaized.net/hls/live/2002689/skynewsau-extra1/master.m3u8',
    logo: 'https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/512/512/skychb1404.png',
    category: 'Dünya / Haber',
    country: 'gb',
  },
  {
    id: 'tv-nasatv',
    name: 'NASA TV',
    type: 'tv',
    url: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/512px-NASA_logo.svg.png',
    category: 'Dünya / Belgesel',
    country: 'us',
  },

  // RADYO KANALLARI
  {
    id: 'radio-powerturk',
    name: 'PowerTürk',
    type: 'radio',
    url: 'https://listen.powerapp.com.tr/powerturk/mpeg/icecast.audio',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Power_T%C3%BCrk_logo.svg/512px-Power_T%C3%BCrk_logo.svg.png',
    category: 'Türkçe Pop',
  },
  {
    id: 'radio-joyfm',
    name: 'Joy FM',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/JOY_FM.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Joy_FM_logo.png/512px-Joy_FM_logo.png',
    category: 'Yabancı Slow',
  },
  {
    id: 'radio-virgin',
    name: 'Virgin Radio',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/VIRGIN_RADIO.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Virgin_Radio_logo.svg/512px-Virgin_Radio_logo.svg.png',
    category: 'Yabancı Hit',
  },
  {
    id: 'radio-metrofm',
    name: 'Metro FM',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/METRO_FM.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Metro_FM_logo.png/512px-Metro_FM_logo.png',
    category: 'Yabancı Hit',
  },
  {
    id: 'radio-powerfm',
    name: 'Power FM',
    type: 'radio',
    url: 'https://listen.powerapp.com.tr/powerfm/mpeg/icecast.audio',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Power_FM_logo.svg/512px-Power_FM_logo.svg.png',
    category: 'Yabancı Hit',
  },
  {
    id: 'radio-superfm',
    name: 'Süper FM',
    type: 'radio',
    url: 'https://21633.live.streamtheworld.com:443/SUPER_FM.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/S%C3%BCper_FM_logo.png/512px-S%C3%BCper_FM_logo.png',
    category: 'Türkçe Pop',
  },
  {
    id: 'radio-kexp',
    name: 'KEXP 90.3',
    type: 'radio',
    url: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/KEXP_logo.svg/512px-KEXP_logo.svg.png',
    category: 'Yabancı Müzik',
    country: 'us',
  },

  // ===== TÜRK RADYOLARI (EK) =====
  {
    id: 'radio-trtspor',
    name: 'TRT Spor Radyo',
    type: 'radio',
    url: 'https://radio-trtspor.medya.trt.com.tr/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/TRT_Spor_Radyo_logo.svg/512px-TRT_Spor_Radyo_logo.svg.png',
    category: 'Spor',
  },

  // ===== ULUSLARARASI KANALLAR =====
  // ABD
  {
    id: 'tv-bloombergus',
    name: 'Bloomberg TV+',
    type: 'tv',
    url: 'https://bloomberg.com/media-manifest/streams/us.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Bloomberg_logo.svg/512px-Bloomberg_logo.svg.png',
    category: 'Dünya / Ekonomi',
    country: 'us',
  },
  // İngiltere
  {
    id: 'radio-bbcradio1',
    name: 'BBC Radio 1',
    type: 'radio',
    url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/BBC_Radio_1_logo.svg/512px-BBC_Radio_1_logo.svg.png',
    category: 'Yabancı Pop',
    country: 'gb',
  },
  {
    id: 'radio-bbcmusic',
    name: 'BBC Radio 2',
    type: 'radio',
    url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/BBC_Radio_2_logo.svg/512px-BBC_Radio_2_logo.svg.png',
    category: 'Yabancı Pop',
    country: 'gb',
  },
  // Almanya
  {
    id: 'radio-antennede',
    name: 'Antenne Bayern',
    type: 'radio',
    url: 'https://stream.antenne.de/antenne/stream/mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Antenne_Bayern_Logo.svg/512px-Antenne_Bayern_Logo.svg.png',
    category: 'Yabancı Pop',
    country: 'de',
  },
  // Fransa
  // Katar
  {
    id: 'tv-aljazeera-eng',
    name: 'Al Jazeera English',
    type: 'tv',
    url: 'https://live-hls-web-aje-fa.thehlive.com/AJE/index.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Aljazeera_eng.svg/512px-Aljazeera_eng.svg.png',
    category: 'Dünya / Haber',
    country: 'qa',
  },

  // ===== ABD (Ek) =====
  {
    id: 'radio-npr',
    name: 'NPR News',
    type: 'radio',
    url: 'https://npr-ice.streamguys1.com/live.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/NPR_logo.svg/512px-NPR_logo.svg.png',
    category: 'Yabancı Haber',
    country: 'us',
  },

  // ===== İngiltere (Ek) =====
  {
    id: 'radio-bbcworld',
    name: 'BBC World Service',
    type: 'radio',
    url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/BBC_World_Service_logo_%282022%29.svg/512px-BBC_World_Service_logo_%282022%29.svg.png',
    category: 'Yabancı Haber',
    country: 'gb',
  },
  {
    id: 'radio-classicfm',
    name: 'Classic FM',
    type: 'radio',
    url: 'https://media-ice.musicradio.com/ClassicFMMP3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Classic_FM_logo.svg/512px-Classic_FM_logo.svg.png',
    category: 'Yabancı Klasik',
    country: 'gb',
  },
  {
    id: 'radio-capital',
    name: 'Capital FM',
    type: 'radio',
    url: 'https://media-ice.musicradio.com/CapitalMP3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Capital_FM_logo.svg/512px-Capital_FM_logo.svg.png',
    category: 'Yabancı Hit',
    country: 'gb',
  },

  // ===== Almanya (Ek) =====
  {
    id: 'radio-1live',
    name: '1LIVE',
    type: 'radio',
    url: 'https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/1LIVE_logo.svg/512px-1LIVE_logo.svg.png',
    category: 'Yabancı Pop',
    country: 'de',
  },

  // ===== Fransa (Ek) =====
  {
    id: 'radio-rfi',
    name: 'RFI Monde',
    type: 'radio',
    url: 'https://rfimonde64k.ice.infomaniak.ch/rfimonde-64.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/RFI_logo_2014.svg/512px-RFI_logo_2014.svg.png',
    category: 'Yabancı Haber',
    country: 'fr',
  },
  {
    id: 'radio-fip',
    name: 'FIP',
    type: 'radio',
    url: 'https://icecast.radiofrance.fr/fip-hifi.aac',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/FIP_logo_2019.svg/512px-FIP_logo_2019.svg.png',
    category: 'Yabancı Müzik',
    country: 'fr',
  },
  {
    id: 'radio-franceinter',
    name: 'France Inter',
    type: 'radio',
    url: 'https://icecast.radiofrance.fr/franceinter-hifi.aac',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/France_Inter_2021_logo.svg/512px-France_Inter_2021_logo.svg.png',
    category: 'Yabancı Haber',
    country: 'fr',
  },

  // ===== İtalya =====
  {
    id: 'radio-rai1',
    name: 'Rai Radio 1',
    type: 'radio',
    url: 'https://icestreaming.rai.it/1.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Radio1_Logo.png/512px-Radio1_Logo.png',
    category: 'Yabancı Haber',
    country: 'it',
  },
  {
    id: 'radio-rai2',
    name: 'Rai Radio 2',
    type: 'radio',
    url: 'https://icestreaming.rai.it/2.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Radio_2_Logo.png/512px-Radio_2_Logo.png',
    category: 'Yabancı Müzik',
    country: 'it',
  },

  // ===== İspanya =====
  {
    id: 'radio-los40',
    name: 'LOS40',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/LOS40_logo.svg/512px-LOS40_logo.svg.png',
    category: 'Yabancı Hit',
    country: 'es',
  },

  // ===== Hollanda =====
  {
    id: 'radio-538',
    name: 'Radio 538',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Radio_538_logo.svg/512px-Radio_538_logo.svg.png',
    category: 'Yabancı Hit',
    country: 'nl',
  },
  {
    id: 'radio-qmusic',
    name: 'Qmusic',
    type: 'radio',
    url: 'https://stream.qmusic.nl/qmusic/mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Qmusic-logo.svg/512px-Qmusic-logo.svg.png',
    category: 'Yabancı Hit',
    country: 'nl',
  },

  // ===== Avustralya =====
  {
    id: 'radio-triplej',
    name: 'triple j',
    type: 'radio',
    url: 'https://live-radio01.mediahubaustralia.com/2TRI/aac/',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Triple_J_logo.svg/512px-Triple_J_logo.svg.png',
    category: 'Yabancı Müzik',
    country: 'au',
  },
  {
    id: 'radio-abcfm',
    name: 'ABC Sydney',
    type: 'radio',
    url: 'https://live-radio01.mediahubaustralia.com/2FMW/mp3/',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Australian_Broadcasting_Corporation_logo.svg/512px-Australian_Broadcasting_Corporation_logo.svg.png',
    category: 'Yabancı Haber',
    country: 'au',
  },

  // ===== Kanada =====

  // ===== Japonya =====

  // ===== ABD (Ek 2) =====
  {
    id: 'radio-somafm',
    name: 'SomaFM Groove Salad',
    type: 'radio',
    url: 'https://ice1.somafm.com/groovesalad-128-mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/SomaFM_logo.svg/512px-SomaFM_logo.svg.png',
    category: 'Yabancı Müzik',
    country: 'us',
  },

  // ===== İngiltere (Ek 2) =====
  {
    id: 'radio-bbcradio3',
    name: 'BBC Radio 3',
    type: 'radio',
    url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/BBC_Radio_3_logo.svg/512px-BBC_Radio_3_logo.svg.png',
    category: 'Yabancı Klasik',
    country: 'gb',
  },
  {
    id: 'radio-bbcradio4',
    name: 'BBC Radio 4',
    type: 'radio',
    url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/BBC_Radio_4_logo_2022.svg/512px-BBC_Radio_4_logo_2022.svg.png',
    category: 'Yabancı Haber',
    country: 'gb',
  },
  {
    id: 'radio-lbc',
    name: 'LBC News',
    type: 'radio',
    url: 'https://media-ice.musicradio.com/LBCUKMP3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/LBC_logo.svg/512px-LBC_logo.svg.png',
    category: 'Yabancı Haber',
    country: 'gb',
  },

  // ===== Almanya (Ek 2) =====

  // ===== Fransa (Ek 2) =====
  {
    id: 'radio-europe1',
    name: 'Europe 1',
    type: 'radio',
    url: 'https://stream.europe1.fr/europe1.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Europe_1_logo_2019.svg/512px-Europe_1_logo_2019.svg.png',
    category: 'Yabancı Haber',
    country: 'fr',
  },

  // ===== İtalya (Ek) =====
  {
    id: 'radio-rai3',
    name: 'Rai Radio 3',
    type: 'radio',
    url: 'https://icestreaming.rai.it/3.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Rai_Radio_3_logo_2022.svg/512px-Rai_Radio_3_logo_2022.svg.png',
    category: 'Yabancı Klasik',
    country: 'it',
  },

  // ===== İspanya (Ek) =====
  {
    id: 'radio-cadenaser',
    name: 'Cadena SER',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Cadena_SER_logo_2023.svg/512px-Cadena_SER_logo_2023.svg.png',
    category: 'Yabancı Haber',
    country: 'es',
  },
  {
    id: 'radio-radiole',
    name: 'Radiolé',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOLE.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Radiol%C3%A9_logo.svg/512px-Radiol%C3%A9_logo.svg.png',
    category: 'Yabancı Müzik',
    country: 'es',
  },

  // ===== Hollanda (Ek) =====
  {
    id: 'radio-nporadio2',
    name: 'NPO Radio 2',
    type: 'radio',
    url: 'https://icecast.omroep.nl/radio2-bb-mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/NPO_Radio_2_logo_2014.svg/512px-NPO_Radio_2_logo_2014.svg.png',
    category: 'Yabancı Pop',
    country: 'nl',
  },
  {
    id: 'radio-skyradio',
    name: 'Sky Radio',
    type: 'radio',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/SKYRADIO.mp3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Sky_Radio_logo_2021.svg/512px-Sky_Radio_logo_2021.svg.png',
    category: 'Yabancı Hit',
    country: 'nl',
  },

  // ===== Avustralya (Ek) =====
  {
    id: 'radio-doublej',
    name: 'Double J',
    type: 'radio',
    url: 'https://live-radio01.mediahubaustralia.com/2DJJ/aac/',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Double_J_logo.svg/512px-Double_J_logo.svg.png',
    category: 'Yabancı Müzik',
    country: 'au',
  },
  {
    id: 'radio-abcnewsradio',
    name: 'ABC NewsRadio',
    type: 'radio',
    url: 'https://live-radio02.mediahubaustralia.com/2PBW/aac/',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Australian_Broadcasting_Corporation_logo.svg/512px-Australian_Broadcasting_Corporation_logo.svg.png',
    category: 'Yabancı Haber',
    country: 'au',
  },
];
